# This file tells Docker how to build and run the application.
# It specifies the services that make up the application, and how they interact.


version: '3'
services:
  app:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5000:5000"
    depends_on:
      - quiz-postgres

  quiz-postgres:
    image: postgres:latest
    container_name: quiz-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - quiz_data:/var/lib/postgresql/data

volumes:
  quiz_data:
