version: '3'
services:
  db:
    image: postgres:latest
    container_name: quizDb
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - quiz_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  quiz_data:
